"""Add cascade delete to user reviews

Revision ID: 40f19937762a
Revises: 4e40e785596f
Create Date: 2025-06-02 15:25:17.973385

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '40f19937762a'
down_revision = '4e40e785596f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(
            'user_reviews_user_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None, 'users', ['user_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'user_reviews_user_id_fkey', 'users', ['user_id'], ['id']
        )

    # ### end Alembic commands ###
