"""Initial migrations.

Revision ID: 66f0fb947c1f
Revises: 
Create Date: 2025-04-20 15:54:20.661378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f0fb947c1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('user_favorites',
    sa.Column('place_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'user_id', name='unique_place_user')
    )
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_favorites_place_id'), ['place_id'], unique=False)

    op.create_table('user_reviews',
    sa.Column('images', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('place_id', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'user_id', name='unique_place_user_review')
    )
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reviews_place_id'), ['place_id'], unique=False)

    op.create_table('review_reactions',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['user_reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='unique_review_user')
    )
    with op.batch_alter_table('review_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_reactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_reactions_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_reactions_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_reactions_id'))

    op.drop_table('review_reactions')
    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reviews_place_id'))
        batch_op.drop_index(batch_op.f('ix_user_reviews_id'))

    op.drop_table('user_reviews')
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorites_place_id'))
        batch_op.drop_index(batch_op.f('ix_user_favorites_id'))

    op.drop_table('user_favorites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
