"""add trip_status to user_trips

Revision ID: da13c03b9a5c
Revises: f611a1169c34
Create Date: 2025-06-03 15:03:15.603349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da13c03b9a5c'
down_revision = 'f611a1169c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_status', sa.Boolean(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE user_trips SET trip_status = false")
    
    # Make the column not nullable after setting default values
    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.alter_column('trip_status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.drop_column('trip_status')

    # ### end Alembic commands ###
