"""Add cascade delete to all user relationships

Revision ID: f611a1169c34
Revises: 40f19937762a
Create Date: 2025-06-02 15:36:30.479471

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f611a1169c34'
down_revision = '40f19937762a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint('trips_trip_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'user_trips', ['trip_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.drop_constraint(
            'user_favourites_user_id_fkey', type_='foreignkey'
        )
        batch_op.create_foreign_key(
            None, 'users', ['user_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.drop_constraint('user_trips_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'users', ['user_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'user_trips_user_id_fkey', 'users', ['user_id'], ['id']
        )

    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'user_favourites_user_id_fkey', 'users', ['user_id'], ['id']
        )

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'trips_trip_id_fkey', 'user_trips', ['trip_id'], ['id']
        )

    # ### end Alembic commands ###
