"""Update vector_items tables

Revision ID: faf94828434a
Revises: da13c03b9a5c
Create Date: 2025-06-20 16:44:25.370498

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'faf94828434a'
down_revision = 'da13c03b9a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vector_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vector_items', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
